### PR TITLE
Validator updates

### PR DESCRIPTION
**Pull request by baughj**
This PR updates the validator with some new features:

* Add method for selecting world directory
* Add output / status window with messages
* Add checkbox for validate all / button for clear output
* Remove xml editor stuff

### CODE REVIEW

**Comment by Fluffguck** [comment]
👎 for HKCU root.

**Comment by norrismiv** [comment]
looks good

**Comment by norrismiv** [comment]
i liked the old fuckery better

**Comment by norrismiv** [comment]
i liked the old fuckery better

**Comment by Fluffguck** [comment]
👍 from one helmet wearer, very accomodating

**Comment by Fluffguck** [comment]
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by baughj** [comment]
I PUT REGISTRY KEYS WHERE I WANT
I DON'T FOLLOW THE RULES OF YOUR SYSTEM

**Pull request merged**
